receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  # Add resource attributes
  resource:
    attributes:
      - key: environment
        value: development
        action: upsert

exporters:
  # Debug exporter - prints to console
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

  # Send traces to Jaeger
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Prometheus metrics exporter
  prometheus:
    endpoint: "0.0.0.0:8889"

  # File exporter for logs
  file:
    path: /tmp/otel-logs.json
    rotation:
      max_megabytes: 10
      max_days: 3
      max_backups: 3
      localtime: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  zpages:
    endpoint: 0.0.0.0:55679
  pprof:
    endpoint: 0.0.0.0:1777

service:
  extensions: [health_check, zpages, pprof]
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug, otlp/jaeger]
    
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug, prometheus]
    
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug, file]