services:
  seq-test:
    image: datalust/seq
    container_name: seq-test
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "8080:80"
      - "5342:5341"

  es-test:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: es-test
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  splunk-test:
    image: splunk/splunk:latest
    container_name: splunk-test
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
      - SPLUNK_HEC_TOKEN=00000000-0000-0000-0000-000000000000
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"