name: Analyzer Release

on:
  push:
    tags:
      - 'analyzer/v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release Analyzer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false

    - name: Extract version from tag
      id: version
      run: |
        # Extract version from tag (e.g., analyzer/v1.0.0 -> v1.0.0)
        TAG="${GITHUB_REF#refs/tags/}"
        VERSION="${TAG#analyzer/}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
        workdir: cmd/mtlog-analyzer
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}