name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Extract version from tag
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Extract changelog
      id: changelog
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        # Extract the section for this version from CHANGELOG.md
        CHANGELOG=$(awk "/^## ${VERSION}/ {p=1; next} /^## / {p=0} p" CHANGELOG.md)
        
        # Handle multi-line output
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: ${{ steps.version.outputs.version }}
        body: |
          ## What's Changed
          
          ${{ steps.changelog.outputs.changelog }}
          
          ## Installation
          
          ```bash
          go get github.com/willibrandon/mtlog@${{ steps.version.outputs.version }}
          ```
          
          **Full Changelog**: https://github.com/${{ github.repository }}/compare/v0.0.1...${{ steps.version.outputs.version }}
        draft: false
        prerelease: false